### ISSUE TITLE
01 Write a testsuite

### ISSUE THREAD

**Issue by RLeenings** [wwu-mmll/photonai_brainhack23#5]
- [x] Provide methods to iterate different datasets
- [x] Maybe prepare the LifeScience datasets from [UCI data repository](https://archive.ics.uci.edu/datasets?skip=0&take=10&sort=desc&orderBy=NumHits&search=&Area=Life+Science) (~147) 
- [x] Iterate over the datasets

**Comment by jernsting** [comment]
Please feel free to split up this issue into smaller ones.

**Comment by jernsting** [comment]
I will try to include https://pypi.org/project/uci-dataset/

**Comment by jernsting** [comment]
At least they provide some classification datasets
